### PR TITLE
Adding EAP-MSCHAPv2 support

### PR DESCRIPTION
**Pull request by enaess**
Implementation based on the RFC: draft-kamath-pppext-eap-mschapv2-02.
Adding support for MSCHAPv2 inside extensible authentication protocol (EAP).

Original author: Thomas Omerzu <thomas@omerzu.de>.

### CODE REVIEW

**Comment by paulusmack** [comment]
At the very least this needs a Signed-off-by line.  See Submitting-patches.md.

**Comment by Neustradamus** [comment]
@enaess: Can you update your PR?

**Comment by enaess** [comment]
Update the PR w.r.t. current code? Yes, I will do this later today, or early tomorrow morning. I did submit the patch to the mailing list. Do you want me to do both, or is there specific instructions on the "Signed-off-by-line" that needs to be included in the PR?

**Comment by enaess** [comment]
@Neustradamus - Could you please help me understand what you want me to do?

**Comment by enaess** [comment]
I am sorry, but merging paulusmack/ppp into enaess/ppp didn't seem to be the right thing and now it wants to merge back 15 changes and not 1. Did update the Signed-off-by line on the one change as you asked, but are either one of you able to cherry pick this one change from my fork instead of the 15 others, or do you want me to re-do the entire pull request?

**Comment by Neustradamus** [comment]
@paulusmack: Please look the question of @enaess...

**Comment by enaess** [comment]
@paulusmack - I'd be willing to do the work and you can always email me privately / skype me if you need to.

**Comment by Neustradamus** [comment]
@enaess: Please try to rebase...

**Comment by enaess** [comment]
@Neustradamus @paulusmack  - I did open a new Pull Request, it's same patch. I could delete this PR and use that instead. Let me know if this works for you guys.

**Comment by Neustradamus** [comment]
@enaess: Thanks!
- https://github.com/paulusmack/ppp/pull/175

@paulusmack: Can you look?

**Comment by paulusmack** [comment]
Superseded by #175.

**Pull request closed without merging**
