### PR TITLE
pppd: remove __P

### PR DESCRIPTION
**Pull request by neheb**
__P is normally defined in sys/cdefs.h , which musl does not have.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by paulusmack** [comment]
I actually want to get rid of __P entirely.

**Comment by neheb** [comment]
Sounds better.

**Comment by neheb** [comment]
```
git grep __P | wc -l
884
```

Oh boy...

**Comment by neheb** [comment]
Updated to remove __P.

**Comment by paulusmack** [comment]
Unfortunately this doesn't compile.  I get:
```
make[1]: Entering directory '/home/paulus/ppp/ppp/pppd'
cc -O2 -pipe -Wall -g -DHAVE_PATHS_H -DIPX_CHANGE -DHAVE_MMAP -I../include '-DDESTDIR="/usr/local"' -DCHAPMS=1 -DMPPE=1 -DHAS_SHADOW -DHAVE_CRYPT_H=1 -DHAVE_LOGWTMP=1 -I/usr/include/openssl -DHAVE_MULTILINK -DUSE_TDB=1 -DPLUGIN -DINET6=1 -DMAXOCTETS   -c -o main.o main.c
main.c:160:26: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘)’ token
  160 | int (*holdoff_hook)(void)) = NULL;
      |                          ^
main.c:161:27: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘)’ token
  161 | int (*new_phase_hook)(int)) = NULL;
      |                           ^
main.c:162:51: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘)’ token
  162 | void (*snoop_recv_hook)(unsigned char *p, int len)) = NULL;
      |                                                   ^
main.c:163:51: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘)’ token
  163 | void (*snoop_send_hook)(unsigned char *p, int len)) = NULL;
      |                                                   ^
main.c:223:1: error: expected declaration specifiers or ‘...’ before ‘}’ token
  223 | };
      | ^
main.c:223:1: error: expected ‘;’, ‘,’ or ‘)’ before ‘}’ token
main.c:225:1: error: expected specifier-qualifier-list before ‘static’
  225 | static struct subprocess *children;
      | ^~~~~~
```
followed by a bunch more errors, and indeed on line 160 of main.c there is an extra ')'.

**Comment by neheb** [comment]
Fixed. Compiles now.

**Comment by Neustradamus** [comment]
@paulusmack: Have you looked the update of this PR?

**Comment by Neustradamus** [comment]
@neheb: Can you rebase this PR?
Thanks in advance.

**Comment by neheb** [comment]
Rebased. Doesn't compile locally for different reasons (clang will not compile this).

**Comment by Neustradamus** [comment]
@neheb: Not good if it is not possible to compile :/

**Comment by neheb** [comment]
It's because other parts of the codebase use nested functions, which are a GCC extension and not part of C.

**Comment by paulusmack** [comment]
I did this myself, so this is redundant now.

**Comment by Neustradamus** [comment]
Commit: https://github.com/paulusmack/ppp/commit/75870d7b55e36af526a0786fff94912989c73fd1

**Pull request closed without merging**
