### PR TITLE
pppd: use monotonic clock source for callouts

### PR DESCRIPTION
**Pull request by pkeroulas**
gettimeofday() isn't the best suitable function to compute duration.
It is prone to fail when the system time changes. Using the monotonic
clock as a time source makes it more resilient.

Signed-off-by: Patrick Keroulas <patrick.keroulas@savoirfairelinux.com>

### CODE REVIEW

**Comment by fhost** [comment]
You wrote `cmonotonic clock` in the error message, is this a typo or we do say `cmonotonic`?

I think more places should need the update from `gettimeofday()` to `clock_gettime(MONOTONIC_CLOCK)`:
- pppd/tty.c:1075
- pppd/tty.c:1124
- pppd/main.c:525
- pppd/main.c:1233
- pppd/plugins/rp-pppoe/discovery.c:48
- pppd/plugins/rp-pppoe/discovery.c:364
- pppd/plugins/rp-pppoe/discovery.c:548

But anyway, this is a great update!

**Comment by pkeroulas** [comment]
Correct, this is a typo.

This commit only addresses callout timings. The other `gettimeofday()` should be replaced in later changes so that eventual regression will be easier to identified. I'll see what I can do.

**Comment by fhost** [comment]
You correct your typo only once, but it is present in all error messages you've changed.

**Comment by thjc** [comment]
This week I ran into issues with clock stepping blocking connection changes. I have tested this patch and it is working for me. Is it able to be merged as is, or is it desired to have the other instances replaced before merging it?

**Comment by themiron** [comment]
jfyi, https://github.com/paulusmack/ppp/pull/123
should be more general solution

**Comment by paulusmack** [comment]
I pulled #123.

**Pull request closed without merging**
