### PR TITLE
Improve musl libc Linux build without breaking other systems compatibility

### PR DESCRIPTION
**Pull request by RICCIARDI-Adrien**

### CODE REVIEW

**Comment by Neustradamus** [comment]
@RICCIARDI-Adrien: Can you update your PR?

@paulusmack: What do you think about this one?

**Comment by RICCIARDI-Adrien** [comment]
@Neustradamus Sure ! I will wait for paulusmack feedback, if he agrees I will update the PR as soon as possible.

**Comment by Neustradamus** [comment]
@RICCIARDI-Adrien: Maybe you can rebase before the feedback of @paulusmack...

**Comment by RICCIARDI-Adrien** [comment]
Hi @Neustradamus, I just rebased. I will try to build it, but I do not have anymore the board to test it. Could you please check if it runs fine ?

**Comment by Neustradamus** [comment]
@RICCIARDI-Adrien: Thanks!

@paulusmack: Can you look it ?
It is up-to-date now ^^

**Comment by paulusmack** [comment]
I fixed this slightly differently, so I'm closing this as superseded.

**Comment by Neustradamus** [comment]
@yegorich, @mjeveritt, @Polynomial-C, @RICCIARDI-Adrien, @jku: Have you tested, perfect for you?

Linked to:
- https://github.com/paulusmack/ppp/issues/51
- https://github.com/paulusmack/ppp/issues/73
- https://github.com/paulusmack/ppp/commit/7555728c50db87ae7d5b8c018c006a14bf374584

**Pull request closed without merging**
