### PR TITLE
Fix netif_set_mtu for Solaris

### PR DESCRIPTION
**Pull request by Low-power**
Replaces #58

### CODE REVIEW

**Comment by paulusmack** [comment]
This is going to need more explanation - what is the problem fixed by this commit, how does it manifest itself, how come no-one has considered the current behavior as a bug before, and why this change is the right way to fix it.

**Comment by Low-power** [comment]
As I already explaned in #58, option `mtu <mtu>` won't have any effect without this patch.

**Comment by Low-power** [comment]
Because this bug exists in Solaris specific codes, it won't affects any users that using the program with Linux. Bugs will always there left unsolved, if no one care.

**Comment by paulusmack** [comment]
Perhaps I needed to be more explicit. When I said "this needs more explanation", I meant in the commit message itself. I intend the ppp git repository to be understandable by itself without reference to github.com. This is not the usual sort of github project where the git metadata is essentially useless and all the useful explanations exist only on github.com.

Also, the sign-off line needs a real name, not just initials.

Since it's Solaris, I will want James Carlson to give his ack on this before I merge it, as I have no way to test Solaris.

**Comment by Low-power** [comment]
Updated with detailed commit message.

The sign `WHR` was my real name, I use it to identify myself in many places. If you can't accept that, take this pull request as a bug report. I think the commit message contains enough information on what the bug is and how to fix it.

**Comment by Neustradamus** [comment]
@Low-power: Can you sign like other people?
Please look last merged PRs.

@paulusmack: The PR is good except it?

**Comment by Neustradamus** [comment]
@Low-power: Can you add a description and sign-off please?

@paulusmack: You have cited James Carlson, he is on GitHub?
Have you seen with to test this PR?

**Comment by Neustradamus** [comment]
@carlsonj: It is for you, what do you think?

**Comment by carlsonj** [comment]
As a fix, this looks fine to me.  If I were doing the work, I'd yank out both of those statics -- neither link_mtu nor link_mru is connected to anything.  They're set and then never used.

**Comment by Neustradamus** [comment]
@Low-power: Can you update this description here: https://github.com/paulusmack/ppp/pull/103#issue-200258643
It must be clear to people...

And add the sign-off?
- https://github.com/paulusmack/ppp/blob/master/Submitting-patches.md

@carlsonj: Thanks for your comment.
Have you looked the Solaris issue that I have tagged you?

**Comment by carlsonj** [comment]
On 2020-12-30 10:36, Neustradamus wrote:
> @Low-power <https://github.com/Low-power>: Can you update this
> description here: #103 (comment)
> <https://github.com/paulusmack/ppp/pull/103#issue-200258643>
> It must be clear to people...
> 
> And add the sign-off?
> 
>   * https://github.com/paulusmack/ppp/blob/master/Submitting-patches.md
> 
> @carlsonj <https://github.com/carlsonj>: Thanks for your comment.
> Have you looked the Solaris issue that I have tagged you?

If you're asking me to do something, I'm sorry, but I really don't have
a clue what you're asking me to do.

Happy to look at diffs if you have some.  Afraid my day job doesn't
involve any 'git' at all, so I'm just lost here.

-- 
James Carlson         42.703N 71.076W         <carlsonj@workingcode.com>

**Comment by Neustradamus** [comment]
@carlsonj: Only to say your point of view of:
- https://github.com/paulusmack/ppp/issues/163

**Pull request merged**
