### PR TITLE
Handle IPv6 RADIUS attributes

### PR DESCRIPTION
**Pull request by alarig**
Handling of IPv6 RADIUS dictionary attributes, see issue #89

### CODE REVIEW

**Comment by Neustradamus** [comment]
@alarig: Thanks :)

I hope that @paulusmack will look it soon...

**Comment by Neustradamus** [comment]
@alarig: Thanks :)
But please look: "All checks have failed", can you solve it?

And I hope that @paulusmack will look it soon...

**Comment by Neustradamus** [comment]
@alarig: The error is "The sign-off is missing.", can you do it?

**Comment by paulusmack** [comment]
Not only is the signoff missing, but the commit description is also missing.

The actual code change looks OK at a quick glance.

**Comment by alarig** [comment]
I added the signed off by and modified the MR title, I hope it’s OK for you

**Comment by Neustradamus** [comment]
@alarig: Thanks, I think that you can add a perfect description here too: https://github.com/paulusmack/ppp/pull/176#issue-518476443 :)

If you have other patches, please create other PRs too...

**Comment by alarig** [comment]
Done too ;)

**Pull request merged**
